CREATE TABLE IF NOT EXISTS stadium(name 		VARCHAR(30) NOT NULL,
								   id           INT 		PRIMARY KEY,
								   teamName 	VARCHAR(30) NOT NULL,
								   address 	    VARCHAR(50) NOT NULL,
								   city 		VARCHAR(20) NOT NULL,
								   state 		VARCHAR(5)  NOT NULL,
								   country      VARCHAR(10) NOT NULL,
								   zip 		    VARCHAR(7)  NOT NULL,
								   phoneNum 	VARCHAR(15) NOT NULL,
								   openDate     VARCHAR(20) NOT NULL,
								   maxSeatCap   INT 		NOT NULL,
								   maxTimeFrame VARCHAR(30),
								   minSeatCap   INT 		NOT NULL,
								   minTimeFrame VARCHAR(30),
                                   grassType    VARCHAR(15) NOT NULL,
								   league       VARCHAR(3)  NOT NULL);
                     
CREATE TABLE IF NOT EXISTS souvenirs(name 	   VARCHAR(20),
								     price 	   FLOAT,
								     stadiumID INT);
                       
CREATE TABLE IF NOT EXISTS edges(id  INT NOT NULL,
							     c0  INT NOT NULL,
							     c1  INT NOT NULL,
							     c2  INT NOT NULL,
							     c3  INT NOT NULL,
							     c4  INT NOT NULL,
							     c5  INT NOT NULL,
							     c6  INT NOT NULL,
							     c7  INT NOT NULL,
							     c8  INT NOT NULL,
							     c9  INT NOT NULL,
							     c10 INT NOT NULL,
							     c11 INT NOT NULL,
							     c12 INT NOT NULL,
                                 c13 INT NOT NULL,
							     c14 INT NOT NULL,
							     c15 INT NOT NULL,
							     c16 INT NOT NULL,
							     c17 INT NOT NULL,
							     c18 INT NOT NULL,
							     c19 INT NOT NULL,
							     c20 INT NOT NULL,
							     c21 INT NOT NULL,
							     c22 INT NOT NULL,
							     c23 INT NOT NULL,
							     c24 INT NOT NULL,
							     c25 INT NOT NULL,
							     c26 INT NOT NULL,
							     c27 INT NOT NULL,
							     c28 INT NOT NULL,
							     c29 INT NOT NULL);