INSERT INTO stadium VALUES ("Angels Stadium of Anaheim",
							0,
							"Los Angeles Angels of Anaheim",
                            "2000 E Gene Autry Way",
                            "Anaheim",
                            "CA",
                            "US",
                            "92806",
                            "714-940-2000",
                            "April 19, 1966",
                            45483,
                            "",
                            45483,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Comerica Park",
							1,
							"Detroit Tigers",
                            "2100 Woodward Ave",
                            "Detroit",
                            "MI",
                            "US",
                            "48201",
                            "313-962-4000",
                            "April 11, 2000",
                            41681,
                            "",
                            41681,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Fenway Park",
							2,
							"Boston Red Sox",
                            "4 Yawkey Way",
                            "Boston",
                            "MA",
                            "US",
                            "02215",
                            "877-733-7699",
                            "April 20, 1912",
                            37071,
                            "Day",
                            37499,
                            "Night",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Globe Life Park in Arlington",
							3,
							"Texas Rangers",
                            "1000 Ballpark Way",
                            "Arlington",
                            "TX",
                            "US",
                            "76011",
                            "817-273-5222",
                            "April 1, 1994",
                            48114,
                            "",
                            48114,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Kauffman Stadium",
							4,
							"Kansas City Royals",
                            "1 Royal Way",
                            "Kansas City",
                            "MO",
                            "US",
                            "64129",
                            "816-921-8000",
                            "April 10, 1973",
                            37903,
                            "",
                            37903,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Minute Maid Park",
							5,
							"Houston Astros",
                            "501 Crawford St.",
                            "Houston",
                            "TX",
                            "US",
                            "77002",
                            "713-259-8000",
                            "March 30, 2000",
                            42060,
                            "",
                            42060,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("O.co Coliseum",
							6,
						    "Oakland Athletics",
                            "7000 Coliseum Way",
						    "Oakland",
                            "CA",
						    "US",
                            "94621",
                            "510-569-2121",
                            "September 18, 1966",
                            55945,
                            "Sept - Jan",
                            37090,
                            "April - August",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Oriole Park at Camden Yards",
							7,
                            "Baltimore Orioles",
                            "333 West Camden Street",
                            "Baltimore",
                            "MD",
                            "US",
                            "21201",
                            "410-685-9800",
                            "April 6, 1992",
                            48187,
                            "",
                            48187,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Progressive Field",
							8,
                            "Cleveland Indians",
                            "2401 Ontario Street",
                            "Cleveland",
                            "OH",
                            "US",
                            "44115",
                            "216-420-4487",
                            "April 2, 1994",
                            42404,
                            "",
                            42404,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Rogers Centre",
							9,
                            "Toronto Blue Jays",
                            "1 Blue Jays Way",
                            "Toronto",
                            "ON",
                            "Canada",
                            "M5V1J3",
                            "1-416-341-1000",
                            "June 3, 1989",
                            49282,
                            "",
                            49282,
                            "",
                            "Astro Turf",
                            "AM");
INSERT INTO stadium VALUES ("SafeCo Field",
							10,
                            "Seattle Mariners",
                            "1516 First Avenue South",
                            "Seattle",
                            "WA",
                            "US",
                            "98134",
                            "206-346-4000",
                            "July 15, 1999",
                            47476,
                            "",
                            47476,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Target Field",
							11,
                            "Minnesota Twins",
                            "353 N 5th St.",
                            "Minneapolis",
                            "MN",
                            "US",
                            "55403",
                            "800-338-9467",
                            "April 12, 2010",
                            39021,
                            "",
                            39021,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Tropicana Field",
							12,
                            "Tampa Bay Rays",
                            "1 Tropicana Dr.",
                            "St. Petersburg",
                            "FL",
                            "US",
                            "33705",
                            "727-825-3137",
                            "March 3, 1990",
                            42735,
                            "Post-season",
                            31042,
                            "Regular season",
                            "Astro Turf",
                            "AM");
INSERT INTO stadium VALUES ("US Cellular Field",
							13,
                            "Chicago White Sox",
                            "333 West 35th Street",
                            "Chicago",
                            "IL",
                            "US",
                            "60616",
                            "312-674-1000",
                            "April 18, 1991",
                            40615,
                            "",
                            40615,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("Yankee Stadium",
							14,
                            "New York Yankees",
                            "1 E 161st St.",
                            "South Bronx",
                            "NY",
                            "US",
                            "10451",
                            "718-293-4300",
                            "April 16, 2009",
                            50291,
                            "",
                            50291,
                            "",
                            "Grass",
                            "AM");
INSERT INTO stadium VALUES ("AT&T Park",
							15,
                            "San Franciso Giants",
                            "24 Willia Mays Plaza",
                            "San Francisco",
                            "CA",
                            "US",
                            "94107",
                            "415-972-2000",
                            "April 11, 2000",
                            41915,
                            "",
                            41915,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Busch Stadium",
							16,
                            "St. Lousi Cardinals",
                            "700 Clark Street",
                            "St. Louis",
                            "MO",
                            "US",
                            "63102",
                            "314-345-9600",
                            "April 10, 2006",
                            46861,
                            "",
                            46861,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Chase Field",
							17,
                            "Arizona Diamondbacks",
                            "401 East Jefferson Street",
                            "Phoenix",
                            "AZ",
                            "US",
                            "85004",
                            "602-462-6500",
                            "March 31, 1998",
                            48633,
                            "",
                            48633,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Citi Field",
							18,
                            "New York Mets",
                            "126th St. & Roosevelt Ave.",
                            "Queens",
                            "NY",
                            "US",
                            "11368",
                            "718-507-6376",
                            "April 13, 2009",
                            41922,
                            "",
                            41922,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Citizens Bank Park",
							19,
                            "Philadelphia Phillies",
                            "1 Citizens Bank Way",
                            "Philadelphia",
                            "PA",
                            "US",
                            "19148",
                            "215-463-1000",
                            "April 3, 2004",
                            43651,
                            "",
                            43651,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Coors Field",
							20,
                            "Colorado Rockies",
                            "2001 Blake St",
                            "Denver",
                            "CO",
                            "US",
                            "80205",
                            "303-292-0200",
                            "April 26, 1995",
                            50480,
                            "",
                            50480,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Dodger Stadium",
							21,
                            "Los Angeles Dodgers",
                            "1000 Elysian Park Avenue",
                            "Los Angeles",
                            "CA",
                            "US",
                            "90090",
                            "323-224-1507",
                            "April 10, 1962",
                            56000,
                            "",
                            56000,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Great American Ball Park",
							22,
                            "Cincinnati Reds",
                            "100 Joe Nuxhall Way",
                            "Cincinnati",
                            "OH",
                            "US",
                            "45202",
                            "513-381-7337",
                            "March 31, 2003",
                            42319,
                            "",
                            42319,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Marlins Park",
							23,
                            "Miani Marlins",
                            "501 Marlins Way",
                            "Miami",
                            "FL",
                            "US",
                            "33125",
                            "305-480-1300",
                            "April 4, 2012",
                            37442,
                            "",
                            37442,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Miller Park",
							24,
                            "Milwaukee Brewers",
                            "1 Brewers Way",
                            "Milwaukee",
                            "WI",
                            "US",
                            "53214",
                            "414-902-4400",
                            "April 6, 2001",
                            41900,
                            "",
                            41900,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Nationals Park",
							25,
                            "Washington Nationals",
                            "1500 S Captiol St SE",
                            "Washington",
                            "DC",
                            "US",
                            "20003",
                            "202-675-6287",
                            "March 30, 2008",
                            41418,
                            "",
                            41418,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Petco Park",
							26,
                            "San Diego Padres",
                            "19 Tony Gwynn Drive",
                            "San Diego",
                            "CA",
                            "US",
                            "92101",
                            "619-975-5000",
                            "April 8, 2004",
                            42524,
                            "",
                            42524,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("PNC Park",
							27,
                            "Pittsburgh Pirates",
                            "115 Federal St",
                            "Pittsburgh",
                            "PA",
                            "US",
                            "15212",
                            "412-321-2827",
                            "March 31, 2001",
                            38362,
                            "",
                            38362,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Turner Field",
							28,
                            "Atlanta Braves",
                            "755 Hank Aaron Drive",
                            "Atlanta",
                            "GA",
                            "US",
                            "30315",
                            "404-522-7630",
                            "March 29, 1997",
                            49586,
                            "",
                            49586,
                            "",
                            "Grass",
                            "NL");
INSERT INTO stadium VALUES ("Wrigley Field",
							29,
                            "Chicago Cubs",
                            "1060 West Addison Street",
                            "Chicago",
                            "IL",
                            "US",
                            "60613",
                            "773-404-2827",
                            "April 23, 1914",
                            42374,
                            "",
                            42374,
                            "",
                            "Grass",
                            "NL");
                            